TOPDIR = $(realpath ..)

SOURCES = startup.c trap.c fault.c
SUBDIR = console floppy graphics loadexec preemption
MYDIRS = tty
SUBDIR += $(MYDIRS)

include $(TOPDIR)/build/build.lib.mk

# vim: ts=8 sw=8 noet
